# Generated by Django 5.2.1 on 2025-05-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Exam Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('exam_type', models.CharField(choices=[('theory', 'theory'), ('practical', 'practical')], default='theory', max_length=20, verbose_name='Exam Type')),
                ('date', models.DateTimeField(verbose_name='Exam Date')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('max_marks', models.PositiveIntegerField(verbose_name='Maximum Marks')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Subject Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
    ]
