# Generated by Django 5.2.1 on 2025-05-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='Category',
            field=models.CharField(choices=[('theory', 'theory'), ('practical', 'practical')], default='theory', max_length=20, verbose_name='Exam Type'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Subject'),
        ),
    ]
