# Generated by Django 5.2.1 on 2025-06-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_category_alter_exam_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='Category',
            field=models.CharField(choices=[('theory', 'theory'), ('practical', 'practical')], default='theory', max_length=20, verbose_name='Exam Category'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final')], default='theory', max_length=20, verbose_name='Exam Type'),
        ),
    ]
