# Generated by Django 5.2.1 on 2025-06-05 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_exam_category_alter_exam_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final')], default='midterm', max_length=20, verbose_name='Exam Type'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.subject', verbose_name='Subject'),
        ),
    ]
