# Generated by Django 5.2.1 on 2025-06-05 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_exam_exam_type_alter_exam_subject'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject', verbose_name='Subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
