# Generated by Django 5.2.1 on 2025-06-05 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_exam_subject_delete_subject'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='class_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.classroom', verbose_name='Class'),
            preserve_default=False,
        ),
    ]
