# Generated by Django 5.2.3 on 2025-06-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
