# Generated by Django 5.2.1 on 2025-06-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other'), ('prefer_not_to_say', 'prefer not to say')], null=True),
        ),
    ]
