# Generated by Django 5.2.1 on 2025-06-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
