# Generated by Django 5.2.3 on 2025-06-17 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('fee', '0002_feetype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='month',
            field=models.ForeignKey(help_text='Month for which the fee is applicable', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.month'),
        ),
    ]
