# Generated by Django 5.2.3 on 2025-06-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0004_alter_studentfee_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='paid_on',
            field=models.DateTimeField(blank=True, help_text='Date when the fee was paid', null=True),
        ),
    ]
