# Generated by Django 5.2.1 on 2025-05-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('admission_number', models.CharField(max_length=20, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('class_room', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('roll_number', models.CharField(max_length=10, null=True, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='cms/student_profiles/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
