# Generated by Django 5.2.1 on 2025-06-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_contact',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
